--Built using postgresSQL
Drop table IF EXISTS TmpAccList;
Drop table IF EXISTS TmpAccLedger;

CREATE TABLE TmpAccList (
	AccountID INT GENERATED BY DEFAULT AS IDENTITY, 
	Name VARCHAR(100),
	IsHeader BIT,
	Parent INT);
ALTER TABLE TmpAccList ADD CONSTRAINT AccountID PRIMARY KEY(AccountID);

Create table TmpAccLedger(
Account INT REFERENCES TmpAccList (AccountID),
Value MONEY);

Insert into TmpAccList(Name, IsHeader,Parent)
VALUES ('Header 100','1',NULL),
	   ('Header 110','1','1'),
	   ('Child 111','0','2'),
	   ('Child 112','0','2'),
	   ('Child 113','0','2'),
	   ('Child 120','0','1'),
	   ('Header 130','1','1'),
	   ('Child 131','0','8'),
	   ('Child 132','0','8'),
	   ('Header 200','1',NULL),
	   ('Header 210','1','11'),
	   ('Child 221','0','12'),
	   ('Child 220','0','11'),
	   ('Header 300','1',NULL),
	   ('Child 310','0','14');

INSERT INTO TmpAccLedger (Account, Value)
VALUES (4,100),
	   (3,50),
	   (5,80),
	   (9,20),
	   (3,10),
	   (8,40),
	   (4,10),
	   (15,30),
	   (12,60),
	   (5,90),
	   (13,100),
	   (8,40),
	   (8,70),
	   (3,50),
	   (3,80),
	   (4,20),
	   (8,10),
	   (3,40),
	   (13,10),
	   (12,30),
	   (5,60),
	   (15,90),
	   (6,100),
	   (15,40),
	   (12,70);
	   
SELECT A.Name, SUM(L.Value)
FROM TmpAccList A
INNER JOIN TmpAccLedger L ON L.Account = A.AccountID
GROUP BY A.Name