--Get same store indicator with start and end dates.
WITH STR_IND AS
(
SELECT
STORE_NUM,
SAME_STORE_IND,
MIN(EFFECTIVE_DATE) AS START_DATE,
MAX(END_DATE) AS END_DATE

FROM
EDWPRD..STORE_HISTORY_DIM

WHERE
SAME_STORE_IND <>'-' AND
STORE_NUM <> '-' AND
CHARACTER_LENGTH(STORE_NUM) = 4 AND
TRIM(SAME_STORE_IND) <> '' AND
(
END_DATE = '9999-12-31'
OR
(END_DATE BETWEEN '2013-01-01' AND '2014-12-31')
)

GROUP BY
STORE_NUM,
SAME_STORE_IND

ORDER BY
STORE_NUM
)
,
--Group by store only using same store indicator and assigning them a number to be added.
STR_GRP AS
(
SELECT
STR_IND.STORE_NUM,
SUM(CASE WHEN STR_IND.SAME_STORE_IND = 'N' THEN 1 ELSE 0 END)  AS NON_COMP,
SUM(CASE WHEN STR_IND.SAME_STORE_IND = 'Y' THEN 1 ELSE 0 END)  AS COMP

FROM
STR_IND

GROUP BY
STR_IND.STORE_NUM

ORDER BY
STR_IND.STORE_NUM
)
,
--Get final same store indicator. This considers any store that had or is in non-comparable status between Jan 01-2013 to Dec 31-2014.
STR_COMP_IND AS
(
SELECT
STR_GRP.STORE_NUM,
(CASE WHEN STR_GRP.NON_COMP = 1 THEN 'N' ELSE 'Y' END) AS COMPARABLE

FROM 
STR_GRP

ORDER BY
STR_GRP.STORE_NUM
)
--------------------------------------------------------------------------------------------------------------------------------------------------------------The final data query
SELECT 
'''' || SD.STORE_NUM AS STORE_NUM,
SCD.STORE_NM,
SD.GEO_CD,
SCD.PROVINCE_ABBREVIATION_NM,
SD.STORE_LOC_ADVERT_MARKET,
SCI.COMPARABLE,
SUM(CASE WHEN CD.C445_YR_NUM = 2014 THEN ((CSIF.ITEM_TRANSACTION_QTY + CSIF.ITEM_RETURN_QUANTITY) * CSIF.ITEM_ACTUAL_SELLING_PRICE_AMT) ELSE 0 END) AS POS_2014,
SUM(CASE WHEN CD.C445_YR_NUM = 2013 THEN ((CSIF.ITEM_TRANSACTION_QTY + CSIF.ITEM_RETURN_QUANTITY) * CSIF.ITEM_ACTUAL_SELLING_PRICE_AMT) ELSE 0 END) AS POS_2013,
PCD.DIVISION_NM,
SUM((CSIF.ITEM_TRANSACTION_QTY + CSIF.ITEM_RETURN_QUANTITY) * CSIF.ITEM_ACTUAL_SELLING_PRICE_AMT) AS POS

FROM
EDWPRD..CTR_SALES_ITEM_FCT CSIF,
EDWPRD..PRODUCT_CURRENT_DIM PCD,
EDWPRD..STORE_CURRENT_DIM SCD,
EDWPRD..CALENDAR_DIM CD,
EDWPRDBW..STORE_DETAILS SD,
STR_COMP_IND SCI

WHERE
CSIF.DAY_ID = CD.DAY_ID AND
CSIF.PRODUCT_ID = PCD.PRODUCT_ID AND
PCD.PRODUCT_NUM_SOURCE_CD = 'IMS' AND
PCD.PRODUCT_NUM<>'N/A' AND
PCD.FINELINE_CD<>'97047' AND
PCD.CORPORATE_STATUS_CD<>'DEL' AND
PCD.SBU_NM = 'Canadian Tire Retail' AND
(PCD.PRODUCT_CLASS_NUM NOT BETWEEN '090' AND '098') AND 
PCD.DIVISION_CD NOT IN ('NM','N/A','00') AND 
CSIF.STORE_ID = SCD.ORGANIZATION_UNIT_ID AND
SD.STORE_NUM = SCD.STORE_NUM AND
SCI.STORE_NUM = SCD.STORE_NUM AND
(C445_YR_NUM BETWEEN 2013 AND 2014)

GROUP BY
SD.STORE_NUM,
SCD.STORE_NM,
SD.GEO_CD,
SCD.PROVINCE_ABBREVIATION_NM,
SD.STORE_LOC_ADVERT_MARKET,
SCI.COMPARABLE,
PCD.DIVISION_NM
;
