CREATE TABLE EDWPRDBW_POS 
(
YR INT, 
QTR INT, 
MTH INT, 
WK INT, 
PROV VARCHAR(50), 
CITY VARCHAR(50), 
DIVISION_CD VARCHAR(2), 
DIVISION_NM VARCHAR(50), 
LOB_CD VARCHAR(2), 
LOB_NM VARCHAR(50), 
CATEGORY_CD VARCHAR(3), 
CATEGORY_NM VARCHAR(50), 
FINELINE_CD VARCHAR(5), 
FINELINE_NM VARCHAR(50), 
STORE_NUM VARCHAR(4), 
STORE_NM VARCHAR(50), 
SIZE_CD VARCHAR(1), 
GEOG_CD VARCHAR(1), 
PRODUCT_NUM VARCHAR(7), 
POS DECIMAL, 
QTY BIGINT
)