CREATE TABLE EDWPRDBW..POS_VIEW_DEAL_ALL_HEATMAP
(
DEAL_TYPE SMALLINT,
PY_TY SMALLINT,
D_WK SMALLINT,
DIVISION_NM VARCHAR(25),
LOB_NM VARCHAR(30),
CATEGORY_CD VARCHAR(3),
CATEGORY_NM VARCHAR(40),
FINELINE_CLASS_NM VARCHAR(40),
FINELINE_CAT_CD VARCHAR(5),
FINELINE_CAT_NM VARCHAR(40),
CONSUMER_ROLE VARCHAR(30),
PRODUCT_PROFILE VARCHAR(30),
NET_POS NUMERIC(9,2),
DAILY_SKU_VIEWS INT
)