DROP TABLE EDWPRDBW..PRODVIEWS;

CREATE TABLE EDWPRDBW..PRODVIEWS AS

(
SELECT
CAST(DAY_DATE AS DATE) AS VIEW_DATE,
(CASE 
        WHEN CHARACTER_LENGTH(LOYALTY_NUMBER_EVAR56) = 0 THEN NULL
        
        WHEN CHARACTER_LENGTH(LOYALTY_NUMBER_EVAR56) > 0 THEN CAST(LOYALTY_NUMBER_EVAR56 AS BIGINT) 
        
END)
        AS LMS,

(CASE
        WHEN CHARACTER_LENGTH(SKU) = 0 THEN NULL        
        
        WHEN SUBSTR(SKU,8,1) = 'P' THEN SUBSTR(SKU,1,7) 

        ELSE SKU 
END) 
        AS PROD_NUM,


PRODUCT_VIEWS_FOR_MERCHANDISING_EVENT12 AS VIEWS

FROM
EDWPRDBW..PRODVIEWS

WHERE

CHARACTER_LENGTH(SKU) > 6 AND
SKU <> 'Undefined'
)
