DELETE

FROM
EDWPRDBW..SKU_LIST
;

INSERT INTO EDWPRDBW..SKU_LIST
SELECT * FROM EXTERNAL 
'X:\Wherever\Tires.csv'
USING (DELIM ',' REMOTESOURCE 'jdbc' IGNOREZERO YES QUOTEDVALUE DOUBLE SKIPROWS 1
LOGDIR 'X:\WhereverLog\'
);
