DROP TABLE EDWPRDBW..HMAP09_AY_JOIN_DATA;

CREATE TABLE EDWPRDBW..HMAP09_AY_JOIN_DATA AS
(
WITH AY AS
(
SELECT
D_WK,
DEAL_TYPE,
FINELINE_CD

FROM
EDWPRDBW..HMAP05_DEALTYPE_SKU_FLN_POS_VIEWS

GROUP BY
D_WK,
DEAL_TYPE,
FINELINE_CD
)

SELECT
AY.D_WK,
AY.DEAL_TYPE,
AY.FINELINE_CD,
(NVL(PY.POS_PY,0) + NVL(TY.POS_TY,0)) AS TOTPOS,
(NVL(PY.VIEWS_PY,0) + NVL(TY.VIEWS_TY,0)) AS TOTVIEW,
(CASE WHEN TOTPOS <> 0 THEN TOTPOS / 2 ELSE 0 END) AS AVE_POS,
(CASE WHEN TOTVIEW <> 0 THEN TOTVIEW / 2 ELSE 0 END) AS AVE_VIEW

FROM
AY
LEFT JOIN
EDWPRDBW..HMAP07_PY_DEALTYPE_FLN_POS_VIEWS PY
ON
AY.D_WK = PY.D_WK AND 
AY.DEAL_TYPE = PY.DEAL_TYPE AND 
AY.FINELINE_CD = PY.FINELINE_CD

LEFT JOIN
EDWPRDBW..HMAP08_TY_DEALTYPE_FLN_POS_VIEWS TY
ON
AY.D_WK = TY.D_WK AND 
AY.DEAL_TYPE = TY.DEAL_TYPE AND 
AY.FINELINE_CD = TY.FINELINE_CD
)
