WITH EDWPRDBW..GROSS_SALES AS
(
SELECT
SCDW.F_YR,
SCDW.F_SEASON,
SCDW.F_QTR,
SCDW.F_WK,
SCD.PROVINCE_ABBREVIATION_NM,
PCD.DIVISION_CD,
PCD.LOB_CD,
PCD.CATEGORY_CD,
SUM((NVL(EWOIF.PURCHASED_QTY,0) * NVL(EWOIF.ITEM_PRICE_AMT,0)) + NVL(EWOIF.ITEM_CORE_CHARGE_AMT,0) + NVL(EWOIF.ITEM_ECO_FEES_AMT,0)) AS SALES

FROM
EDWPRD..PRODUCT_CURRENT_DIM PCD,
EDWPRD..REP_ECOMM_WEB_ORDER_ITEM_FCT EWOIF,
EDWPRD..STORE_CURRENT_DIM SCD,
EDWPRD..ECOMM_ORDER_STATUS_TYPE_DIM EOSTD,
EDWPRD..CALENDAR_DIM CD,
EDWPRDBW..GRP_SHIFTED_CALENDAR_2013_2015_BY_WK SCDW

WHERE
EWOIF.DAY_ID = CD.DAY_ID AND
SCDW.F_YR_SHIFTED = CD.C445_YR_NUM AND
SCDW.F_WK_SHIFT = CD.C445_WK_NUM AND
PCD.PRODUCT_ID = EWOIF.PRODUCT_ID AND
SCD.ORGANIZATION_UNIT_ID = EWOIF.STORE_ID AND
EWOIF.ORDER_ITEM_STATUS_TYPE_ID = EOSTD.ORDER_STATUS_TYPE_ID AND

--(SCDW.F_MTH BETWEEN START_RANGE AND END_RANGE) AND
(SCDW.F_SEASON BETWEEN 2 AND 2) AND 
--(SCDW.F_QTR BETWEEN START_RANGE AND END_RANGE) AND
EOSTD.ORDER_STATUS_CD = 'READY_FOR_PICK_UP' AND
EOSTD.ORDER_LEVEL_ITEM_LEVEL_IND = 'I' AND
PCD.PRODUCT_NUM_SOURCE_CD = 'IMS' AND
PCD.PRODUCT_NUM<>'N/A' AND
PCD.FINELINE_CD<>'97047' AND
PCD.CORPORATE_STATUS_CD<>'DEL' AND
PCD.SBU_NM = 'Canadian Tire Retail' AND
(PCD.PRODUCT_CLASS_NUM NOT BETWEEN '090' AND '098') AND 
PCD.DIVISION_CD NOT IN ('NM','N/A','00')

GROUP BY
SCDW.F_YR,
SCDW.F_SEASON,
SCDW.F_QTR,
SCDW.F_WK,
SCD.PROVINCE_ABBREVIATION_NM,
PCD.DIVISION_CD,
PCD.LOB_CD,
PCD.CATEGORY_CD
)
,
RETURN_SALES AS
(
SELECT
SCDW.F_YR,
SCDW.F_SEASON,
SCDW.F_QTR,
SCDW.F_WK,
SCD.PROVINCE_ABBREVIATION_NM,
PCD.DIVISION_CD,
PCD.LOB_CD,
PCD.CATEGORY_CD,
SUM((NVL(EOICQF.CHANGE_QTY,0) * NVL(EOICQF.ITEM_PRICE_AMT,0)) + NVL(EOICQF.ITEM_CORE_CHARGE_AMT,0) + NVL(EOICQF.ITEM_ECO_FEES_AMT,0)) AS SALES

FROM
EDWPRD..PRODUCT_CURRENT_DIM PCD,
EDWPRD..ECOMM_ORDER_ITEM_CHANGE_QTY_FCT EOICQF,
EDWPRD..ECOMM_ORDER_ITEM_CHANGE_QTY_REASON_DIM EOICQRD,
EDWPRD..STORE_CURRENT_DIM SCD,
EDWPRD..ECOMM_ORDER_STATUS_TYPE_DIM EOSTD,
EDWPRD..CALENDAR_DIM CD,
EDWPRDBW..GRP_SHIFTED_CALENDAR_2013_2015_BY_WK SCDW

WHERE
EOICQF.DAY_ID = CD.DAY_ID AND
SCDW.F_YR_SHIFTED = CD.C445_YR_NUM AND
SCDW.F_WK_SHIFT = CD.C445_WK_NUM AND
PCD.PRODUCT_ID = EOICQF.PRODUCT_ID AND
SCD.ORGANIZATION_UNIT_ID = EOICQF.STORE_ID AND
EOICQF.CHANGE_QTY_REASON_ID = EOICQRD.CHANGE_QTY_REASON_ID AND
EOICQF.ORDER_ITEM_STATUS_TYPE_ID = EOSTD.ORDER_STATUS_TYPE_ID AND

--(SCDW.F_MTH BETWEEN START_RANGE AND END_RANGE) AND
(SCDW.F_SEASON BETWEEN 2 AND 2) AND 
--(SCDW.F_QTR BETWEEN START_RANGE AND END_RANGE) AND
EOSTD.ORDER_STATUS_CD IN('SALESCANCELLED' , 'SALESRETURN') AND 
PCD.PRODUCT_NUM_SOURCE_CD = 'IMS' AND
PCD.PRODUCT_NUM<>'N/A' AND
PCD.FINELINE_CD<>'97047' AND
PCD.CORPORATE_STATUS_CD<>'DEL' AND
PCD.SBU_NM = 'Canadian Tire Retail' AND
(PCD.PRODUCT_CLASS_NUM NOT BETWEEN '090' AND '098') AND 
PCD.DIVISION_CD NOT IN ('NM','N/A','00')

GROUP BY
SCDW.F_YR,
SCDW.F_SEASON,
SCDW.F_QTR,
SCDW.F_WK,
SCD.PROVINCE_ABBREVIATION_NM,
PCD.DIVISION_CD,
PCD.LOB_CD,
PCD.CATEGORY_CD
)
,
GROSS_RETURN_UNION AS
(
SELECT * FROM GROSS_SALES
UNION ALL
SELECT * FROM RETURN_SALES
)

SELECT
F_YR,
F_SEASON,
F_QTR,
F_WK,
PROVINCE_ABBREVIATION_NM,
DIVISION_CD,
LOB_CD,
CATEGORY_CD,
SUM(SALES) AS NET_SALES

FROM
GROSS_RETURN_UNION

GROUP BY
F_YR,
F_SEASON,
F_QTR,
F_WK,
PROVINCE_ABBREVIATION_NM,
DIVISION_CD,
LOB_CD,
CATEGORY_CD
;
