SELECT 
PCD.DIVISION_NM,
PCD.DIVISION_CD,
PCD.LOB_NM,
PCD.LOB_CD,
PCD.CATEGORY_NM,
PCD.CATEGORY_CD,
PCD.SUBCATEGORY_NM,
PCD.SUBCATEGORY_CD,
PCD.FINELINE_NM,
PCD.FINELINE_CD,
PCD.BRAND_NM,
'"''' || PCD.PRODUCT_NUM || '"' AS PRODUCTNUM,
PCD.PRODUCT_ENGLISH_LONG_DESC

FROM
EDWPRD..PRODUCT_CURRENT_DIM PCD

WHERE
PCD.PRODUCT_NUM_SOURCE_CD = 'IMS' AND
PCD.PRODUCT_NUM <> 'N/A' AND
PCD.FINELINE_CD <> '97047' AND
PCD.CORPORATE_STATUS_CD IN('ACT', 'SD', 'TD') AND
PCD.SBU_NM = 'Canadian Tire Retail' AND
(PCD.PRODUCT_CLASS_NUM NOT BETWEEN '090' AND '098') AND 
PCD.DIVISION_CD Not In ('NM','N/A','00') AND
(
UPPER(PCD.BRAND_NM) LIKE '%MASTERCRAFT%'
-- OR
--PCD.CATEGORY_CD = '318'
)

GROUP BY
PCD.DIVISION_NM,
PCD.DIVISION_CD,
PCD.LOB_NM,
PCD.LOB_CD,
PCD.CATEGORY_NM,
PCD.CATEGORY_CD,
PCD.SUBCATEGORY_NM,
PCD.SUBCATEGORY_CD,
PCD.FINELINE_NM,
PCD.FINELINE_CD,
PCD.BRAND_NM,
PRODUCTNUM,
PCD.PRODUCT_ENGLISH_LONG_DESC
;
