INSERT INTO EDWPRDBW..POS_VIEW_HEATMAP_ALL
(
PY_TY,
D_WK,
DIVISION_NM,
LOB_NM,
CATEGORY_CD,
CATEGORY_NM,
FINELINE_CLASS_NM,
FINELINE_CAT_CD,
FINELINE_CAT_NM,
CONSUMER_ROLE,
PRODUCT_PROFILE,
NET_POS,
DAILY_SKU_VIEWS
)

WITH
GETPY AS
(
SELECT
R12PDATA.PY_TY,
R12PDATA.D_WK,
R12PDATA.DIVISION_NM,
R12PDATA.LOB_NM,
R12PDATA.CATEGORY_CD,
R12PDATA.CATEGORY_NM,
R12PDATA.FINELINE_CLASS_NM,
R12PDATA.FINELINE_CAT_CD,
R12PDATA.FINELINE_CAT_NM,
R12PDATA.CONSUMER_ROLE,
R12PDATA.PRODUCT_PROFILE,
SUM(R12PDATA.NET_POS) AS PY_POS,
SUM(R12PDATA.DAILY_SKU_VIEWS) AS PY_VIEWS

FROM
EDWPRDBW..PRODVIEW_POS

WHERE
R12PDATA.PY_TY = 0

GROUP BY
R12PDATA.PY_TY,
R12PDATA.D_WK,
R12PDATA.DIVISION_NM,
R12PDATA.LOB_NM,
R12PDATA.CATEGORY_CD,
R12PDATA.CATEGORY_NM,
R12PDATA.FINELINE_CLASS_NM,
R12PDATA.FINELINE_CAT_CD,
R12PDATA.FINELINE_CAT_NM,
R12PDATA.CONSUMER_ROLE,
R12PDATA.PRODUCT_PROFILE
),

GETTY AS
(
SELECT
R12TDATA.PY_TY,
R12TDATA.D_WK,
R12TDATA.DIVISION_NM,
R12TDATA.LOB_NM,
R12TDATA.CATEGORY_CD,
R12TDATA.CATEGORY_NM,
R12TDATA.FINELINE_CLASS_NM,
R12TDATA.FINELINE_CAT_CD,
R12TDATA.FINELINE_CAT_NM,
R12TDATA.CONSUMER_ROLE,
R12TDATA.PRODUCT_PROFILE,
SUM(R12TDATA.NET_POS) AS TY_POS,
SUM(R12TDATA.DAILY_SKU_VIEWS) AS TY_VIEWS

FROM
EDWPRDBW..PRODVIEW_POS

WHERE
R12TDATA.PY_TY = 1

GROUP BY
R12TDATA.PY_TY,
R12TDATA.D_WK,
R12TDATA.DIVISION_NM,
R12TDATA.LOB_NM,
R12TDATA.CATEGORY_CD,
R12TDATA.CATEGORY_NM,
R12TDATA.FINELINE_CLASS_NM,
R12TDATA.FINELINE_CAT_CD,
R12TDATA.FINELINE_CAT_NM,
R12TDATA.CONSUMER_ROLE,
R12TDATA.PRODUCT_PROFILE
),

TY_PRIMARY AS 
(
SELECT
TY.PY_TY,
TY.D_WK,
TY.DIVISION_NM,
TY.LOB_NM,
TY.CATEGORY_CD,
TY.CATEGORY_NM,
TY.FINELINE_CLASS_NM,
TY.FINELINE_CAT_CD,
TY.FINELINE_CAT_NM,
TY.CONSUMER_ROLE,
TY.PRODUCT_PROFILE,
TY.TY_POS,
(CASE WHEN (TY.TY_VIEWS > 0 AND (PY.PY_VIEWS = 0 OR PY.PY_VIEWS IS NULL)) THEN TY.TY_VIEWS * 2 ELSE TY.TY_VIEWS END) AS TY_VIEW_FACT

FROM
GETTY TY
LEFT JOIN
GETPY PY
ON 
TY.D_WK = PY.D_WK AND
TY.DIVISION_NM = PY.DIVISION_NM AND
TY.LOB_NM = PY.LOB_NM AND
TY.CATEGORY_NM = PY.CATEGORY_NM AND 
TY.FINELINE_CLASS_NM = PY.FINELINE_CLASS_NM AND
TY.FINELINE_CAT_CD = PY.FINELINE_CAT_CD AND
TY.FINELINE_CAT_NM = PY.FINELINE_CAT_NM AND
TY.CONSUMER_ROLE = PY.CONSUMER_ROLE AND
TY.PRODUCT_PROFILE = PY.PRODUCT_PROFILE
),

PY_PRIMARY AS 
(
SELECT
PY.PY_TY,
PY.D_WK,
PY.DIVISION_NM,
PY.LOB_NM,
PY.CATEGORY_CD,
PY.CATEGORY_NM,
PY.FINELINE_CLASS_NM,
PY.FINELINE_CAT_CD,
PY.FINELINE_CAT_NM,
PY.CONSUMER_ROLE,
PY.PRODUCT_PROFILE,
PY.PY_POS,
PY.PY_VIEWS

FROM
GETPY PY
LEFT JOIN
GETTY TY
ON 
PY.D_WK = TY.D_WK AND
PY.DIVISION_NM = TY.DIVISION_NM AND
PY.LOB_NM = TY.LOB_NM AND
PY.CATEGORY_NM = TY.CATEGORY_NM AND 
PY.FINELINE_CLASS_NM = TY.FINELINE_CLASS_NM AND
PY.FINELINE_CAT_CD = TY.FINELINE_CAT_CD AND
PY.FINELINE_CAT_NM = TY.FINELINE_CAT_NM AND
PY.CONSUMER_ROLE = TY.CONSUMER_ROLE AND
PY.PRODUCT_PROFILE = TY.PRODUCT_PROFILE
)

SELECT 
*
FROM 
TY_PRIMARY 

UNION ALL

SELECT
*
FROM
PY_PRIMARY
;

