WITH GETPOS AS
(
SELECT 
CD.C445_YR_NUM,
CD.C445_WK_NUM,
SCD.STORE_NUM,
CSIF.POS_TRANSACTION_ID,
SUM((CSIF.ITEM_TRANSACTION_QTY + CSIF.ITEM_RETURN_QUANTITY) * CSIF.ITEM_ACTUAL_SELLING_PRICE_AMT) AS POS,
SUM(CSIF.ITEM_TRANSACTION_QTY + CSIF.ITEM_RETURN_QUANTITY) AS QTY

FROM
EDWPRD..CTR_SALES_ITEM_FCT CSIF,
EDWPRD..PRODUCT_CURRENT_DIM PCD,
EDWPRD..STORE_CURRENT_DIM SCD,
EDWPRD..CALENDAR_DIM CD

WHERE
CSIF.DAY_ID = CD.DAY_ID AND
CSIF.PRODUCT_ID = PCD.PRODUCT_ID AND
PCD.PRODUCT_NUM_SOURCE_CD = 'IMS' AND
PCD.PRODUCT_NUM<>'N/A' AND
PCD.FINELINE_CD<>'97047' AND
PCD.CORPORATE_STATUS_CD<>'DEL' AND
PCD.SBU_NM = 'Canadian Tire Retail' AND
(PCD.PRODUCT_CLASS_NUM NOT BETWEEN '090' AND '098') AND 
PCD.DIVISION_CD Not In ('NM','N/A','00') AND 
CSIF.STORE_ID = SCD.ORGANIZATION_UNIT_ID AND
(CD.C445_YR_NUM BETWEEN 2013 AND 2015)

GROUP BY
CD.C445_YR_NUM,
CD.C445_WK_NUM,
SCD.STORE_NUM,
CSIF.POS_TRANSACTION_ID
)

SELECT
GP.C445_YR_NUM,
GP.C445_WK_NUM,
GP.STORE_NUM,
COUNT(GP.POS_TRANSACTION_ID) AS BASKETS

FROM 
GETPOS GP

GROUP BY
GP.C445_YR_NUM,
GP.C445_WK_NUM,
GP.STORE_NUM
;
