WITH
BasketGrp AS
(
SELECT
SCDgrp.STORE_NUM,
SCDgrp.PROVINCE_NM,
CSFgrp.DAY_ID,
SUBSTR(CSFgrp.TRANSACTION_TM,1,2) AS ByHr,
CSFgrp.POS_TRANSACTION_ID,
Sum(CSIF.ITEM_TRANSACTION_QTY * CSIF.ITEM_ACTUAL_SELLING_PRICE_AMT) AS GrpPOS

FROM
EDWPRD..CTR_SALES_FCT CSFgrp
INNER JOIN
EDWPRD..STORE_CURRENT_DIM SCDgrp
ON
CSFgrp.STORE_ID = SCDgrp.ORGANIZATION_UNIT_ID
INNER JOIN
EDWPRD..CTR_SALES_ITEM_FCT CSIF
ON
CSFgrp.POS_TRANSACTION_ID = CSIF.POS_TRANSACTION_ID AND
CSFgrp.DAY_ID = CSIF.DAY_ID
INNER JOIN
EDWPRD..PRODUCT_CURRENT_DIM PCD
ON
PCD.PRODUCT_ID = CSIF.PRODUCT_ID

WHERE
(CSFgrp.DAY_ID BETWEEN 20141001 AND 20141010) AND
PCD.PRODUCT_NUM_SOURCE_CD = 'IMS' AND
PCD.SBU_NM = 'Canadian Tire Retail' AND
(PCD.PRODUCT_CLASS_NUM NOT BETWEEN '090' And '098') And 
PCD.PRODUCT_CLASS_NUM <> '00' AND
PCD.DIVISION_CD In ('AU','SP','HA','GS','FX')

GROUP BY
SCDgrp.STORE_NUM,
SCDgrp.PROVINCE_NM,
CSFgrp.DAY_ID,
ByHr,
CSFgrp.POS_TRANSACTION_ID

HAVING
GrpPOS > 0
)

SELECT
Bcnt.STORE_NUM,
Bcnt.PROVINCE_NM,
CD.CLNDR_YR_NUM,
CD.CLNDR_QTR_NUM,
CD.CLNDR_MTH_NUM,
CD.C445_WK_NUM,
CD.DAY_DATE,
Bcnt.DAY_ID,
Bcnt.ByHr,
COUNT(Bcnt.POS_TRANSACTION_ID) AS BasketCnt,
SUM(Bcnt.GrpPOS) AS GrossPOS

FROM
BasketGrp Bcnt,
EDWPRD..CALENDAR_DIM CD

WHERE
CD.DAY_ID = Bcnt.DAY_ID

GROUP BY
Bcnt.STORE_NUM,
Bcnt.PROVINCE_NM,
CD.CLNDR_YR_NUM,
CD.CLNDR_QTR_NUM,
CD.CLNDR_MTH_NUM,
CD.C445_WK_NUM,
CD.DAY_DATE,
Bcnt.DAY_ID,
Bcnt.ByHr

ORDER BY
Bcnt.STORE_NUM,
Bcnt.PROVINCE_NM,
CD.CLNDR_YR_NUM,
CD.CLNDR_QTR_NUM,
CD.CLNDR_MTH_NUM,
CD.C445_WK_NUM,
Bcnt.DAY_ID,
Bcnt.ByHr
;

