SELECT 
PROVINCE_NM,
CD.C445_YR_NUM,
PCD.DIVISION_NM,
PCD.CATEGORY_NM,
SUM((CSIF.ITEM_TRANSACTION_QTY + CSIF.ITEM_RETURN_QUANTITY) * CSIF.ITEM_ACTUAL_SELLING_PRICE_AMT) AS POS,
SUM(CSIF.ITEM_TRANSACTION_QTY + CSIF.ITEM_RETURN_QUANTITY) AS QTY

FROM
EDWPRD..CTR_SALES_ITEM_FCT CSIF,
EDWPRD..PRODUCT_CURRENT_DIM PCD,
EDWPRD..STORE_CURRENT_DIM SCD,
EDWPRD..CALENDAR_DIM CD

WHERE
CSIF.DAY_ID = CD.DAY_ID AND
CSIF.PRODUCT_ID = PCD.PRODUCT_ID AND
PCD.PRODUCT_NUM_SOURCE_CD = 'IMS' AND
PCD.PRODUCT_NUM<>'N/A' AND
PCD.FINELINE_CD<>'97047' AND
PCD.CORPORATE_STATUS_CD<>'DEL' AND
PCD.FINELINE_CD<>'97047' AND
PCD.PRODUCT_NUM_SOURCE_CD = 'IMS' AND
PCD.SBU_NM = 'Canadian Tire Retail' AND
(PCD.PRODUCT_CLASS_NUM NOT BETWEEN '090' And '098') And 
PCD.DIVISION_CD Not In ('NM','N/A','00') AND 
CSIF.STORE_ID = SCD.ORGANIZATION_UNIT_ID AND
CD.C445_YR_NUM BETWEEN 2009 AND 2014

GROUP BY
PROVINCE_NM,
CD.C445_YR_NUM,
PCD.DIVISION_NM,
PCD.CATEGORY_NM
;
