SELECT 
SCDW.F_YR,
SCDW.F_SEASON,
SCDW.F_QTR,
SCDW.F_WK,
SCD.PROVINCE_ABBREVIATION_NM,
PCD.DIVISION_CD,
PCD.LOB_CD,
PCD.CATEGORY_CD,
SUM((CSIF.ITEM_TRANSACTION_QTY + CSIF.ITEM_RETURN_QUANTITY) * CSIF.ITEM_ACTUAL_SELLING_PRICE_AMT) AS POS

FROM
EDWPRD..CTR_SALES_ITEM_FCT CSIF,
EDWPRD..PRODUCT_CURRENT_DIM PCD,
EDWPRD..STORE_CURRENT_DIM SCD,
EDWPRD..CALENDAR_DIM CD,
EDWPRDBW..GRP_SHIFTED_CALENDAR_2013_2015_BY_WK SCDW

WHERE
CSIF.DAY_ID = CD.DAY_ID AND
SCDW.F_YR_SHIFTED = CD.C445_YR_NUM AND
SCDW.F_WK_SHIFT = CD.C445_WK_NUM AND
CSIF.PRODUCT_ID = PCD.PRODUCT_ID AND
CSIF.STORE_ID = SCD.ORGANIZATION_UNIT_ID AND

--(SCDW.F_MTH BETWEEN START_RANGE AND END_RANGE) AND
(SCDW.F_SEASON BETWEEN 2 AND 2) AND 
--(SCDW.F_QTR BETWEEN START_RANGE AND END_RANGE) AND
PCD.PRODUCT_NUM_SOURCE_CD = 'IMS' AND
PCD.PRODUCT_NUM<>'N/A' AND
PCD.FINELINE_CD<>'97047' AND
PCD.CORPORATE_STATUS_CD<>'DEL' AND
PCD.SBU_NM = 'Canadian Tire Retail' AND
(PCD.PRODUCT_CLASS_NUM NOT BETWEEN '090' AND '098') AND 
PCD.DIVISION_CD NOT IN ('NM','N/A','00')

GROUP BY
SCDW.F_YR,
SCDW.F_SEASON,
SCDW.F_QTR,
SCDW.F_WK,
SCD.PROVINCE_ABBREVIATION_NM,
PCD.DIVISION_CD,
PCD.LOB_CD,
PCD.CATEGORY_CD
;
