SELECT 
SCDW.F_YR,
SCDW.F_SEASON,
SCDW.F_QTR,
SCDW.F_MTH,
SCDW.F_WK,
W.PROVINCE_ABBREVIATION_NM,
AVG(NVL(W.MAXIMUM_TEMPERATURE_AMT,0)) AS MAXTEMP,
AVG(NVL(W.MINIMUM_TEMPERATURE_AMT,0)) AS MINTEMP,
AVG(NVL(W.PRECIPITATION_MM_AMT,0)) AS AVEPREC,
AVG(NVL(W.SNOW_CM_AMT,0)) AS AVESNOW

FROM
EDWPRD..CALENDAR_DIM CD,
EDWPRDBW..GRP_WEATHER W,
EDWPRDBW..GRP_SHIFTED_CALENDAR_2013_2015_BY_WK SCDW

WHERE
W.WEATHER_DATE = CD.DAY_DATE AND
SCDW.F_WK_SHIFT  = CD.C445_WK_NUM AND
SCDW.F_YR_SHIFTED = CD.C445_YR_NUM AND

SCDW.F_MTH = GET_MTH AND
UPPER(W.WEATHER_DATATYPE_CD) = 'OBS'

GROUP BY
SCDW.F_YR,
SCDW.F_SEASON,
SCDW.F_QTR,
SCDW.F_MTH,
SCDW.F_WK,
W.PROVINCE_ABBREVIATION_NM
;
